apiVersion: yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: yb-test-1
  namespace: yb-demo
spec:
  replicationFactor: 3
  master:
    replicas: 3
    storage:
      size: 10Gi
  tserver:
    replicas: 3
    storage:
      count: 1
      size: 10Gi
