kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yugabyte-operator-crb
  namespace: yb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yugabyte-operator-role
subjects:
  - kind: ServiceAccount
    name: yugabyte-operator
    namespace: yb-operator
